version: '3.8'

services:
  ad-agency-dapp:
    image: ad-agency-dapp:latest
    container_name: ad-agency-dapp
    restart: always
#    networks:
#      - traefik-proxy
    ports:
      - 3000:3000
#    environment:
#      ENVIRONMENT: "prod"
#      PORT: ${PORT}
#    healthcheck:
#      test: curl --fail -s http://localhost:3000/ || exit 1
#      interval: 10s
#      retries: 2
#      start_period: 5s
#      timeout: 3s
    cpus: 0.9 # 90%
    mem_reservation: 10m
    mem_limit: 1g
#    labels:
#      traefik.enable: true
#      traefik.docker.network: traefik-proxy # required due to 2 networks
#      traefik.http.routers.scrapers.rule: Host(`${MAIN_DOMAIN}`)
#      traefik.http.routers.scrapers.entrypoints: https
#      traefik.http.routers.scrapers.tls.certResolver: desec
#      traefik.http.services.scrapers.loadbalancer.server.port: 3000

#      com.centurylinklabs.watchtower.enable: false


#networks:
#  traefik-proxy:
#    external: true
